### ISSUE TITLE
Prompt for folder name

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs-5666-scatt-gp#1]

**Comment by haietza** [comment]
- [ ] Verify that folder exists

- [ ] Verify that folder is not empty

Assumption: .jar is being run from current working directory where folder exists.

**Comment by KaraBeason** [comment]
@haietza @caldwellc1 I could use some help w/ unit testing.  My method seems to work from manual testing but the unit test is bombing.  I could use some fresh eyes.  My branch is 1- openFolder.  thanks!

**Comment by haietza** [comment]
@KaraBeason It looks like you called folder.newFolder for the directory, but not folder.newFile for the file. The test is failing on the testFile.exists() so it looks like it's not seeing the test file. I think they also suggest only using one assert call per test - so each one can be more granular.

**Comment by KaraBeason** [comment]
@haietza I've tried just about every variation of this I can... still not working.  I think I'm going to change direction and stop trying to use temporary folders... as nice as they would be.  Thanks for the help
