### ISSUE TITLE
JSON parser for Java

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs-5666-scatt-gp#10]
Write parser class to read JSON file. Consider using http://www.mkyong.com/java/json-simple-example-read-and-write-json/?

**Comment by KaraBeason** [comment]
@haietza @caldwellc1 I need a bit of clarity on the scope of this story.  Do I need to write a class with methods to get the appropriate object counts?  Can it be part of FileUtils instead?  I guess I'm just not sure what the ouput of the parsing is supposed to look like for this issue to be "done"

**Comment by haietza** [comment]
@KaraBeason No - the Submission class will have the functions to get the appropriate object counts. I was thinking we put the JSON parser code in FileUtils (since it's just generic to reading a JSON file, nothing specific to SCATT)y, then we can call that function from the Submission class to parse the object's JSON file and then call the functions from the Submission class on the Submission object to get the counts. If you want to push up the code you have so far, we can take a look and maybe help? Or let me know if we need to get together before Thursday. Thanks!

**Comment by KaraBeason** [comment]
@haietza I pushed up what I did last night.  It's parsing, and I can grab the first value... I'm just not really sure where to go from there.  I'm going to play around with it for a bit to see how to access some of the more "nested" values.

**Comment by haietza** [comment]
@KaraBeason I just discovered some more tweaks I need to make to the Submission class (like storing the json file in a File object after it is unzipped, so we can properly call the parser on each included json file for each Submission object). I'll open a new branch for that, and that might make testing easier for the parser too.

I was not able to get the existing parser code to run manually to see what is being returned specifically. I think we have 2 options - we can either parse the whole document into an array of some sort, and then pull the count info out of that - OR we can just parse for the specific things we are interested in and only pull that data as we parse. I think option 1 might make our code more OCP compliant (so if we change what we are counting or reporting on in the future, we'll already have that info in the array and we'll just need to write Submission functions to get it and return it to the report) but option 2 is certainly simpler in design. I think option 1 is probably simpler to code, and I think the likelihood of us making changes to what data we get is pretty high at this point in the project, so I would suggest, for simplicity of code and OCP - maybe try to parse the JSON contents into an array?

**Comment by KaraBeason** [comment]
@haietza I will push up my changes, I threw some stuff in the main method to see what it's getting but didn't have time to thoroughly inspect it.  I will look into it some more tonight.

I agree with you about parsing the JSON into an array.  To clarify, are we are talking about a java array, or a JSONArray (like part of simple JSON)?  That helps clarify this issue for me a bit.  I will think about how/what we should be parsing into (what should the output look like after parsing) and work on it more when I am home in ~ an hour!
Thanks!

**Comment by haietza** [comment]
@KaraBeason I was sort of thinking we'd use the JSONArray, but I hadn't looked into the API enough to know if there were advantages/disadvantages of that versus a Java array. I guess let's try that to start unless we discover a reason not to?

Thanks for the note for running it manually - that worked perfectly! Now I see how the parser is working - once we see how we can get the parsed contents into an array, that will give me an idea of how to test and code the methods in the Submission class to get/count the data for the report.

**Comment by KaraBeason** [comment]
@haietza @caldwellc1 I have made some changes.  Made some design decisions I'm not sure about, bc it's making it kind of difficult to unit test the parsing method (I know I am terrible and didn't do test first).  If ya'll had time could you take a look and give me your thoughts?? thanks!

**Comment by haietza** [comment]
@KaraBeason So your plan is the parseJSONFile() method creates the Submission jsonObj object, then getJSONAttribute(name) returns the String value for that attribute, and you'll be adding on similar to that for the JSONArray? I think that's what we discussed, and so far that sounds like the direction we should move in. Let me know if I'm misunderstanding something though :). Thanks!!

**Comment by KaraBeason** [comment]
@haietza You got it!  I have added the getJSONArrayAttribute, but my unit test is failing with seemingly identical output.  I opened a PR prematurely bc I figured it was a good way to get feedback.
