### ISSUE TITLE
Advanced metrics

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs-5666-scatt-gp#22]
- Determine how many times variables and lists are used in the scripts (stage and per sprite).
- Output ScriptComments for each script (for stage, and for each sprite)
- Output additional information for each variable (name, value); for stage, and for each sprite

**Comment by fenwickjb** [comment]
Excellent! This is one issue I was going to add. 

Not sure what you mean by "persistent" though. 

One other aspect of variables is there "scope." Some are for one sprite only, others are shared with all sprites. This is probably significant and worthy of disaggregating.

**Comment by haietza** [comment]
@fenwickjb - A few questions:
* I see how to determine which variables are actually used in scripts - would it be valuable to just know which variables are used in scripts, or would you also like to have a count of how many times each variable was referenced?
* Each variable in the JSON has an "isPersistent" attribute; however no matter what I do to a variable, it always appears as "false" in the JSON, so perhaps this is not a valuable metric. Do you agree?
* With regard to scope - when a variable is added to the stage, it is available to all sprites (global). When a variable is added to a particular sprite, it is only available to that sprite (local). However, when a variable is added to a particular sprite, but designated as "for all sprites", it just behaves the same as the variable added to the stage (as far as the JSON output). Since we are already providing counts of variables for stage and variables per sprite, does this meet your need for providing this metric?

Thank you!
cc @caldwellc1 @KaraBeason

**Comment by haietza** [comment]
@KaraBeason What do you think about breaking these up into 3 separate issues, for simplicity?

**Comment by KaraBeason** [comment]
@Haietza I would be okay with that!

**Comment by haietza** [comment]
@KaraBeason I'm closing this issue since it has been transferred to #36, #37, #38. I did not assign you to any of them - I figure you can grab 1-3 of them whenever you're ready, and if we need to assign some to @caldwellc1 and/or me, we can do that too. Thanks!!
