### ISSUE TITLE
Block category counts

### ISSUE THREAD

**Issue by fenwickjb** [JaysGitLab/cs-5666-scatt-gp#24]
Not sure if this is in your other list of countable things...

A Scratch program is a collection of interacting sprites. Each sprite has a collection of interacting scripts. Each script is a sequence of blocks. Some blocks allow nesting of other blocks (e.g., loops).

Scratch "categorizes" the 150'ish available blocks by their function. For example, the "Motion" blocks are in the Motion block "palette" and have a dark blue color.

We want to be able to count how many of the Motion blocks are used. Probably want to know this information for all of the various block categories per script, per sprite, per entire program.

**Comment by haietza** [comment]
@fenwickjb I don't see an obvious way to determine the categories for the script blocks in the JSON file; do you know if there is a consistent way to get the script block's category from the JSON file? Or do we need to determine that from the script name and match that up visually in Scratch to its function/category? 

For example, I can see in the JSON file the block name is 'whenClicked'; I can go into Scratch and see that this belongs to the Events function/category. Do we need to create some type of index that gets the script block name and matches that up to its category, versus something already built into the JSON (like a category ID that I'm just not seeing)?

Thanks!
cc @caldwellc1 @KaraBeason

**Comment by haietza** [comment]
Consider using HashMap with block name as key and category as value.
Students can add a custom script in "More blocks. Perhaps count blocks NOT in HashMap to provide count of custom blocks. Future story will look at evaluating custom blocks. (Did they use inputs? How many inputs? etc).

**Comment by haietza** [comment]
@KaraBeason @caldwellc1 Hey girls - I have been working on getting the block category counts, and I believe I have it working for the stage counts. In looking at how to implement this functionality for the sprite counts, I have discovered that it may be a good idea for us to break the Sprite fields and functions out into a separate class, and have an array of Sprite objects field in the Submission class to reference those. That way, we can keep all the related data for a Sprite object separate from the Submission object. What do you guys think?

**Comment by haietza** [comment]
This issue broken out into smaller tasks - #27, #28, #29
