### ISSUE TITLE
Add confirmation message to Report

### ISSUE THREAD

**Issue by haietza** [JaysGitLab/cs-5666-scatt-gp#40]
- Add a confirmation message to standard output to Report that lets the user know their report was successfully created and where they can go to view it.
- Add a timestamp at the top of the report.

**Comment by KaraBeason** [comment]
@haietza @caldwellc1 I was thinking it may be helpful to add a timestamp (datetime) to the report.  Like maybe right after the File name.   What do you think?

**Comment by haietza** [comment]
@KaraBeason @caldwellc1 I agree - I think a timestamp would be helpful. Do you think we need one after each submission filename? Or just a single one at the top for the entire report?

**Comment by KaraBeason** [comment]
@haietza I think a single one at the top would suffice.  I think it should just serve as a unique identifier for that report

**Comment by haietza** [comment]
@KaraBeason Cool - I updated the initial comment with the note for this issue. Thanks!

**Comment by KaraBeason** [comment]
@haietza awesome, thank you!
