### ISSUE TITLE
Consult for sprite information

### ISSUE THREAD

**Issue by fenwickjb** [JaysGitLab/cs-5666-scatt-gp#5]
With Scratch sb2 file unpacked, we can now query for a variety of information including:

- int getSpriteCount() - how many sprites are there

- String[] getSpriteNames() - each sprite has a unique name

- int getScriptCountForSprite(String spriteName) - each sprite can have a number of scripts

etc...

**Comment by haietza** [comment]
See https://github.com/JaysGitLab/cs-5666-scatt-gp/wiki/Metrics for list of metrics to include.
